// GENERATED from command_reference.json and installed packs; do not edit.
export const REFERENCE = {
 "schema": 1,
 "reviewed": "2026-09-05",
 "entries": [
  {
   "id": "core:help",
   "category": "Core server",
   "title": "/help",
   "syntax": "/help [page | command]",
   "summary": "Ask this server for the commands and syntax it actually supports.",
   "example": "/help teleport",
   "permission": "Any player",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "Use this built-in reference after a Minecraft update; this curated guide is not an exhaustive engine command list.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/help?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:list",
   "category": "Core server",
   "title": "/list",
   "syntax": "/list",
   "summary": "See who is currently connected.",
   "example": "/list",
   "permission": "Any player",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/list?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:say",
   "category": "Core server",
   "title": "/say",
   "syntax": "/say <message>",
   "summary": "Send a public server message.",
   "example": "/say Welcome to the server!",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/say?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:tell",
   "category": "Core server",
   "title": "/tell",
   "syntax": "/tell <player> <message>",
   "summary": "Send a private message.",
   "example": "/tell \"Player Two\" Meet at spawn.",
   "permission": "Any player",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "Aliases include /msg and /w. Quote gamertags containing spaces.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/tell?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:time",
   "category": "Core server",
   "title": "/time",
   "syntax": "/time set <day | night | number>",
   "summary": "Change the world's time of day.",
   "example": "/time set day",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "To inspect the current time instead, use /time query daytime.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/time?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:weather",
   "category": "Core server",
   "title": "/weather",
   "syntax": "/weather <clear | rain | thunder> [duration]",
   "summary": "Choose the weather.",
   "example": "/weather clear",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Use /weather query to inspect weather. Check /help weather for the current engine's options.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/weather?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:teleport",
   "category": "Core server",
   "title": "/teleport",
   "syntax": "/tp <player> <destination player>",
   "summary": "Move a player to another player.",
   "example": "/tp @s \"Player Two\"",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Vanilla /tp does not create an admin return point. /help teleport lists coordinate and rotation variants.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/teleport?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:gamemode",
   "category": "Core server",
   "title": "/gamemode",
   "syntax": "/gamemode <mode> [player]",
   "summary": "Change a player's game mode.",
   "example": "/gamemode creative @s",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Common modes: survival, creative, adventure, spectator. @s means the executing player, not the server console.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/gamemode?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:give",
   "category": "Core server",
   "title": "/give",
   "syntax": "/give <player> <item> [amount]",
   "summary": "Give items to a player.",
   "example": "/give @s minecraft:torch 16",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Use a named player instead of @s from the console.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/give?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:effect",
   "category": "Core server",
   "title": "/effect",
   "syntax": "/effect <player> <effect> [seconds] [amplifier]",
   "summary": "Apply a status effect.",
   "example": "/effect @s night_vision 60",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "/effect <player> clear removes effects. Review selectors before affecting more than one player.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/effect?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:gamerule",
   "category": "Core server",
   "title": "/gamerule",
   "syntax": "/gamerule <rule> [value]",
   "summary": "Read or change a world rule.",
   "example": "/gamerule keepinventory",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "Omit the value to inspect a rule. Adding a value changes gameplay; for example keepinventory true changes death behavior.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/gamerule?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:difficulty",
   "category": "Core server",
   "title": "/difficulty",
   "syntax": "/difficulty <peaceful | easy | normal | hard>",
   "summary": "Change world difficulty.",
   "example": "/difficulty normal",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Changing to peaceful can remove hostile mobs.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/difficulty?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:spawnpoint",
   "category": "Core server",
   "title": "/spawnpoint",
   "syntax": "/spawnpoint [player] [x y z]",
   "summary": "Set a player's respawn location.",
   "example": "/spawnpoint @s",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "This changes respawning, not their admin teleport return point.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/spawnpoint?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:setworldspawn",
   "category": "Core server",
   "title": "/setworldspawn",
   "syntax": "/setworldspawn [x y z]",
   "summary": "Set the world's shared spawn location.",
   "example": "/setworldspawn 0 80 0",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Check terrain before changing spawn for everyone.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/setworldspawn?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:kick",
   "category": "Core server",
   "title": "/kick",
   "syntax": "/kick <player> [reason]",
   "summary": "Disconnect a player from this session.",
   "example": "/kick \"Player Two\" Please rejoin.",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "This is not a persistent ban.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/kick?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:op",
   "category": "Core server",
   "title": "/op",
   "syntax": "/op <player>",
   "summary": "Grant operator privileges.",
   "example": "/op \"Exact Gamertag\"",
   "permission": "Admin / server console",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "Only grant this to trusted administrators. Reading this guide does not change anyone's permission.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/op?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:deop",
   "category": "Core server",
   "title": "/deop",
   "syntax": "/deop <player>",
   "summary": "Remove operator privileges.",
   "example": "/deop \"Exact Gamertag\"",
   "permission": "Admin / server console",
   "where": "In game / server console",
   "cheats": "No",
   "notes": "",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/deop?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:allowlist",
   "category": "Core server",
   "title": "/allowlist",
   "syntax": "allowlist <add | remove | list | on | off | reload> [name]",
   "summary": "Manage who may connect.",
   "example": "allowlist list",
   "permission": "Server console (Owner)",
   "where": "Server console only",
   "cheats": "Yes",
   "notes": "Add trusted names before turning it on. The launcher also exposes allowlist editing.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/allowlist?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:save",
   "category": "Core server",
   "title": "/save",
   "syntax": "save <hold | query | resume>",
   "summary": "Coordinate dedicated-server saving.",
   "example": "save query",
   "permission": "Server console (Owner)",
   "where": "Server console only",
   "cheats": "Yes",
   "notes": "Advanced backup workflow: hold suspends saving; always resume afterward. Prefer the launcher's backup action. This is not Java Edition's /save-all.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/save?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:stop",
   "category": "Core server",
   "title": "/stop",
   "syntax": "stop",
   "summary": "Stop the dedicated server.",
   "example": "stop",
   "permission": "Server console (Owner)",
   "where": "Server console only",
   "cheats": "Yes",
   "notes": "Prefer the launcher's Stop button so its Python manager also shuts down. Use /admin:restart for a warned, managed restart.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/stop?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:function",
   "category": "Core server",
   "title": "/function",
   "syntax": "/function <path>",
   "summary": "Run a behavior pack function.",
   "example": "/help function",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "A function may be internal or destructive. Inspect the pack's documentation first; Help never runs one for you.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/function?view=minecraft-bedrock-stable"
  },
  {
   "id": "core:scriptevent",
   "category": "Core server",
   "title": "/scriptevent",
   "syntax": "/scriptevent <namespace:event> [message]",
   "summary": "Send a named event to installed scripts.",
   "example": "/scriptevent mgr:menu",
   "permission": "Operator",
   "where": "In game / server console",
   "cheats": "Yes",
   "notes": "Only documented events should be invoked. Java Edition plugin commands are not automatically available on Bedrock.",
   "status": "Bundled reference",
   "source": "https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/scriptevent?view=minecraft-bedrock-stable"
  },
  {
   "id": "admin:help",
   "category": "Admin tools",
   "title": "/admin:help",
   "syntax": "/admin:help [search]",
   "summary": "Browse core, admin, manager and installed-mod command help.",
   "example": "/admin:help teleport",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Optional search text. This browser is read-only; selecting an entry never executes it.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:menu",
   "category": "Admin tools",
   "title": "/admin:menu",
   "syntax": "/admin:menu",
   "summary": "Open the grouped operator toolbox.",
   "example": "/admin:menu",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Close chat so the in-game form can appear.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:status",
   "category": "Admin tools",
   "title": "/admin:status",
   "syntax": "/admin:status",
   "summary": "Check online count and wait for a fresh manager response.",
   "example": "/admin:status",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "A timeout means no fresh reply; cached restart information is labelled.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:heal",
   "category": "Admin tools",
   "title": "/admin:heal",
   "syntax": "/admin:heal [player]",
   "summary": "Restore one player's health; defaults to yourself.",
   "example": "/admin:heal",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Does not remove effects or extinguish fire.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:feed",
   "category": "Admin tools",
   "title": "/admin:feed",
   "syntax": "/admin:feed [player]",
   "summary": "Refill hunger and saturation and clear exhaustion.",
   "example": "/admin:feed",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Defaults to yourself. Exactly one matched player is required.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:inspect",
   "category": "Admin tools",
   "title": "/admin:inspect",
   "syntax": "/admin:inspect [player]",
   "summary": "Inspect health, mode, location and saved return point.",
   "example": "/admin:inspect",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Private, read-only information. Defaults to yourself.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:goto",
   "category": "Admin tools",
   "title": "/admin:goto",
   "syntax": "/admin:goto <player>",
   "summary": "Visit one player and save your return point.",
   "example": "/admin:goto \"Player Two\"",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Block collisions are checked, but hazards and drops are still your responsibility.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:bring",
   "category": "Admin tools",
   "title": "/admin:bring",
   "syntax": "/admin:bring <player>",
   "summary": "Bring one player to you, saving their previous position.",
   "example": "/admin:bring \"Player Two\"",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Use /admin:return with that player to send them back.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:back",
   "category": "Admin tools",
   "title": "/admin:back",
   "syntax": "/admin:back",
   "summary": "Return to your previous admin teleport location.",
   "example": "/admin:back",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Successful returns swap the two positions. Vanilla /tp and deaths are not tracked.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:return",
   "category": "Admin tools",
   "title": "/admin:return",
   "syntax": "/admin:return <player>",
   "summary": "Return one player to their saved admin teleport location.",
   "example": "/admin:return \"Player Two\"",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Missing, blocked or unloaded destinations fail without forcing the teleport.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:day",
   "category": "Admin tools",
   "title": "/admin:day",
   "syntax": "/admin:day",
   "summary": "Set world time to morning.",
   "example": "/admin:day",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "World-wide time: 1,000 ticks. Menu use asks for confirmation.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:night",
   "category": "Admin tools",
   "title": "/admin:night",
   "syntax": "/admin:night",
   "summary": "Set world time to night.",
   "example": "/admin:night",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "World-wide time: 13,000 ticks. Menu use asks for confirmation.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:clearweather",
   "category": "Admin tools",
   "title": "/admin:clearweather",
   "syntax": "/admin:clearweather",
   "summary": "Clear Overworld weather for ten minutes.",
   "example": "/admin:clearweather",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:announce",
   "category": "Admin tools",
   "title": "/admin:announce",
   "syntax": "/admin:announce \"message\"",
   "summary": "Broadcast a signed announcement.",
   "example": "/admin:announce \"Meet at spawn in five minutes.\"",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "1–180 characters. The menu offers preview/edit/cancel. Direct command use sends immediately.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:restart",
   "category": "Admin tools",
   "title": "/admin:restart",
   "syntax": "/admin:restart",
   "summary": "Confirm a managed restart with a one-minute warning.",
   "example": "/admin:restart",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Requires a fresh Python-manager reply. Watch for the countdown; a sent request is not completion confirmation.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "admin:cancelrestart",
   "category": "Admin tools",
   "title": "/admin:cancelrestart",
   "syntax": "/admin:cancelrestart",
   "summary": "Cancel a pending restart or skip the next scheduled restart.",
   "example": "/admin:cancelrestart",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "No",
   "notes": "Requires the Python manager. If no restart is pending, this skips the next scheduled one.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:menu",
   "category": "Restart manager",
   "title": "/scriptevent mgr:menu",
   "syntax": "/scriptevent mgr:menu",
   "summary": "Open restart, schedule and mod controls.",
   "example": "/scriptevent mgr:menu",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:mods",
   "category": "Restart manager",
   "title": "/scriptevent mgr:mods",
   "syntax": "/scriptevent mgr:mods",
   "summary": "Open the generated Mod Control Center.",
   "example": "/scriptevent mgr:mods",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:admin",
   "category": "Restart manager",
   "title": "/scriptevent mgr:admin",
   "syntax": "/scriptevent mgr:admin",
   "summary": "Open the admin toolbox through the legacy script-event route.",
   "example": "/scriptevent mgr:admin",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:help",
   "category": "Restart manager",
   "title": "/scriptevent mgr:help",
   "syntax": "/scriptevent mgr:help",
   "summary": "Open the unified command-help browser.",
   "example": "/scriptevent mgr:help",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:restart",
   "category": "Restart manager",
   "title": "/scriptevent mgr:restart",
   "syntax": "/scriptevent mgr:restart",
   "summary": "Request the normal warned restart.",
   "example": "/scriptevent mgr:restart",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "Requires the responding Python manager. Unlike /admin:restart, this legacy text command does not show a confirmation dialog.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:cancel",
   "category": "Restart manager",
   "title": "/scriptevent mgr:cancel",
   "syntax": "/scriptevent mgr:cancel",
   "summary": "Cancel a pending restart or skip the next scheduled one.",
   "example": "/scriptevent mgr:cancel",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "Requires the responding Python manager.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:next",
   "category": "Restart manager",
   "title": "/scriptevent mgr:next",
   "syntax": "/scriptevent mgr:next",
   "summary": "Ask the manager to announce the next restart.",
   "example": "/scriptevent mgr:next",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:sync",
   "category": "Restart manager",
   "title": "/scriptevent mgr:sync",
   "syntax": "/scriptevent mgr:sync",
   "summary": "Refresh the cached manager information.",
   "example": "/scriptevent mgr:sync",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  },
  {
   "id": "manager:schedule",
   "category": "Restart manager",
   "title": "/scriptevent mgr:schedule",
   "syntax": "/scriptevent mgr:schedule <HH:MM,HH:MM>",
   "summary": "Change daily restart times using the server's local clock.",
   "example": "/scriptevent mgr:schedule 06:00,14:00,22:00",
   "permission": "Operator",
   "where": "In game only",
   "cheats": "Yes",
   "notes": "Requires the responding Python manager. This persists a schedule change.",
   "status": "Bundled reference",
   "source": "Bundled command_reference.json"
  }
 ],
 "packs": [],
 "warnings": [],
 "notes": "Read-only guide. Core syntax is curated; /help <command> is authoritative for the running build. Mod discovery is best effort. Disabled/uninstalled packs are not available. Dynamic commands require pack documentation.",
 "fingerprint": "a700a0b4dd2d1b03b3b233343eb8de2047588bf0425207591e6dd38f3ae646d0"
};
export const ADMIN_COMMANDS = [["help", "Browse core, admin, manager and installed-mod command help.", "query"], ["menu", "Open the grouped operator toolbox.", ""], ["status", "Check online count and wait for a fresh manager response.", ""], ["heal", "Restore one player's health; defaults to yourself.", "optional"], ["feed", "Refill hunger and saturation and clear exhaustion.", "optional"], ["inspect", "Inspect health, mode, location and saved return point.", "optional"], ["goto", "Visit one player and save your return point.", "required"], ["bring", "Bring one player to you, saving their previous position.", "required"], ["back", "Return to your previous admin teleport location.", ""], ["return", "Return one player to their saved admin teleport location.", "required"], ["day", "Set world time to morning.", ""], ["night", "Set world time to night.", ""], ["clearweather", "Clear Overworld weather for ten minutes.", ""], ["announce", "Broadcast a signed announcement.", "message"], ["restart", "Confirm a managed restart with a one-minute warning.", ""], ["cancelrestart", "Cancel a pending restart or skip the next scheduled restart.", ""]];
